### ISSUE TITLE
RuntimeException in version 1.6.x

### ISSUE THREAD

**Issue by calcosta** [tedious/JShrink#123]
Just updated to version 1.6.

Shrinking several libraries now breaks with `Error: Unclosed string at position:` or `Error: Unclosed regex pattern at position`.

One example is jquery-ui.js (see https://pastebin.com/NwEXPtAb): breaks e.g. on line 12958

I added `$this->echo('|error|');` before `throw new \RuntimeException('Unclosed regex pattern at position: ' . $this->index);` and removed the exception to get an idea where the error occurs. See https://pastebin.com/AX1XFgS3 (starts on line 1074).

Thanks for help!

**Comment by tedivm** [comment]
Thanks for narrowing it down- honestly that is the hardest part of a lot of these bugs, just figuring out where it's breaking. Looking at the line in question I've got a good idea of what's happening, so once I'm done with work today I should be able to tackle it.

**Comment by manavo** [comment]
Not sure if this helps (or if it's the same), but I was able to track down a similar exception with `Error: Unclosed regex pattern at position` to having the combination `g/` but not as part of a regex: `var value = currentRating/other;`  

Failing test:

```php
    public function testUnclosedRegexExceptionDoesNotHappenWithVariablesEndingWithG()
    {
        $this->expectNotToPerformAssertions();
        \JShrink\Minifier::minify('var value = currentRating/other;');
    }

```

**Comment by tedivm** [comment]
Test cases are always super super helpful! I normally put them directly into the test suite when I'm working on fixes.

**Comment by manavo** [comment]
Yeah, I'd include it in a pull request normally, but haven't had a chance to dig into why this is happening. And then I saw an open PR and this issue, so wasn't sure if it's already mostly resolved 🙂

**Comment by tedivm** [comment]
I think I'll be able to resolve it with about an hour of work, but unfortunately last night I had a migraine so I didn't have a chance.

**Comment by manavo** [comment]
No worries at all! Thanks for looking into this as quickly as you are!

**Comment by attrib** [comment]
I'm running into this issue as well.

Maybe my reduced test case helps when trying to test it:

```php
<?php

require 'vendor/autoload.php';

var_dump(JShrink\Minifier::minify('if (spans[jj].className.match(/currentTab.*/)) {
    tabNum = ii;
}'));
```

Returns: `Unclosed regex pattern at position: 49`

I also tried to apply the fix from #124 but the issue remains the same.

**Comment by attrib** [comment]
Actually noticed the above error is the error with the fix applied.

Here an example when it does without #124

```php
<?php

require 'vendor/autoload.php';

var_dump(JShrink\Minifier::minify('if(D>(F/2){console.log("a")}'));

```

Works if I add spaces around the `/`, but doesn't minify it

```
<?php

require 'vendor/autoload.php';

var_dump(JShrink\Minifier::minify('if(D>(F / 2){console.log("a")}'));

```

Results in `if(D>(F / 2){console.log("a")}`
Expected: `if(D>(F/2){console.log("a")}`

**Comment by tedivm** [comment]
A fix has been pushed up! I've incorporated all of the examples from this thread into the test suite as well to prevent future regressions.

Thanks for everyone's help!

**Comment by maciej-orba** [comment]
Ref file: https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/jquery-ui.js

**Comment by maciej-orba** [comment]
Please reopen

**Comment by tedivm** [comment]
@maciej-orba - check out the latest PR, #126, it should resolve this. I've included the jquery-ui test in the test suite itself to confirm that no errors are being triggered.

**Comment by maciej-orba** [comment]
I confirm, Static Content Deploy for Magento works fine, with no issues on latest JShrink
Thank you!

```
adminhtml/Magento/backend/en_US         1825/2923           =================>---------- 62%    6 secs              
frontend/Magento/luma/en_US             1007/2199           ============>--------------- 45%    6 secs
frontend/Magento/blank/en_US            2102/2183           ==========================>- 96%    11 secs             
adminhtml/Magento/backend/en_US         2678/2923           =========================>-- 91%    11 secs             
frontend/Magento/luma/en_US             2099/2199           ==========================>- 95%    11 secs
frontend/Magento/blank/en_US            2183/2183           ============================ 100%   11 secs             
adminhtml/Magento/backend/en_US         2923/2923           ============================ 100%   11 secs             
frontend/Magento/luma/en_US             2199/2199           ============================ 100%   11 secs
Execution time: 14.963996887207
```

**Comment by tedivm** [comment]
Thank you for confirming that- if you have any other issues please feel free to open up an issue here!

**Comment by hendralin** [comment]
Hello, 

I'm still using version 1.6.0 and PHP7, but Error: Unclosed regex pattern at position...still appear.

because since 1.6.1 it dropped PHP 7 support.

is there anyway to patch this error?

I'm now downgrade to 1.5.0

Thank you

**Comment by tedivm** [comment]
I should have dropped php7 support in 1.6 but didn't as an error. You should lock to 1.5 or even 1.4 if you're having trouble and want to stay on the no longer supported php7. You should really upgrade to php8 though, as php7 isn't getting security updates anymore.

**Comment by tedivm** [comment]
I'm going to lock this topic for now- if people find their way here please just open up a new ticket with any issues you're having.
